---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-base:latest

dependencies:
  galaxy: requirements.yml