---
collections:
  - name: ansible.posix
  - name: ansible.utils
    source: https://old-galaxy.ansible.com 
  - name: awx.awx
  - name: containers.podman
  - name: kubernetes.core
  - name: kubevirt.core
  - name: redhatinsights.insights
  - name: community.general
  - name: community.crypto
    source: https://old-galaxy.ansible.com