# Debian like System update Plan
- name: Update to the latest Version (Bug & Security fixes)
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    cache_valid_time: "{{ apt.update_cache_valid_time }}"
    only_upgrade: true
    state: latest # noqa package-latest This role is to update packages.

# Debian Dist Upgrade
- name: Upgrade OS and 
  when: apt.dist_upgrade
  ansible.builtin.apt:
    upgrade: "{{ apt.dist_upgrade_type }}"

# Autoremove package when requested
- name: Apt autoremove (apt)
  when: update_autoremove
  ansible.builtin.apt:
    autoremove: "{{ update_autoremove }}"

# Check for reboot
- name: Check Reboot File exists
  register: reboot_required
  ansible.builtin.stat:
    path: /var/run/reboot-required

# Check if file exist
- name: Check if reboot is required
  when: reboot_required.stat.exists and do_reboot
  ansible.builtin.reboot:
    msg: "Reboot {{ inventory_hostname }}"

- name: Wait for reboot to complete and SSH to become available
  ansible.builtin.wait_for_connection:
    connect_timeout: 30
    delay: 5

- name: Debug System is back
  ansible.builtin.debug:
    msg: "System {{ inventory_hostname }} is Rebooted"
