---
# SUSE Zypper update all packages
- name: Update all packages
  when: not zypper.patch
  community.general.zypper:
    name: '*'
    state: latest
    update_cache: true  

# SUSE Zyper patch only bugfixes & security
- name: Apply only bugfixes & security
  when: zypper.patch
  community.general.zypper:
    name: '*'
    state: latest
    type: patch
    update_cache: true

# SUSE Zyper patch only bugfixes & security
- name: Apply only bugfixes & security
  when: zypper.dist_upgrade
  community.general.zypper:
    name: '*'
    state: dist-upgrade
    allow_vendor_change: true
    update_cache: true

- name: Check to see if we need a reboot
  register: need_reboot_out
  changed_when: '"true" in need_reboot_out.stdout'
  failed_when: need_reboot_out.rc > 1
  ignore_errors: true
  ansible.builtin.shell:
    cmd: needs-restarting -r || echo true

- name: Set reboot Fact
  when: '"true" in need_reboot_out.stdout' 
  ansible.builtin.set_fact:
    system_need_reboot: true