---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: "Include bechtle.linux_update_role"
      ansible.builtin.include_role:
        name: "bechtle.linux_update_role"
