---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

platforms:
  - name: debian-like-system
    namespace: devops
    molecule_user: molecule
    container_image: registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-debian:12
    ssh_service:
      type: ClusterIP

  - name: rhel-like-system
    namespace: devops
    molecule_user: molecule
    container_image: registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-fedora:39
    ssh_service:
      type: ClusterIP

  - name: suse-like-system
    namespace: devops
    molecule_user: molecule
    container_image: registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-opensuse:15
    ssh_service:
      type: ClusterIP

provisioner:
  name: ansible
  log: true

verifier:
  name: ansible
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .

scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy