---
dependency:
  name: galaxy
driver:
  name: kubevirt
platforms:
  - name: ansible-rke2-server-1
    namespace: devops
    molecule_user: molecule
    volumes:
      - name: boot
        containerDisk:
          image: registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-debian-11:latest
          path: /disk/debian-11.qcow2
    ssh_service:
      type: ClusterIP
  - name: ansible-rke2-agent-1
    namespace: devops
    molecule_user: molecule
    volumes:
      - name: boot
        containerDisk:
          image: registry.gitlab-bs.demolab.ch:4567/kubevirt/kubevirt-images/virt-image-debian-11:latest
          path: /disk/debian-11.qcow2
    ssh_service:
      type: ClusterIP
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      ansible-rke2-server-1:
        rke2_type: server
        primary: true
        fqdn: "{{ inventory_name }}.example.com"
      ansible-rke2-agent-1:
        rke2_type: agent
        fqdn: "{{ inventory_name }}.example.com"
verifier:
  name: ansible
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy