---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  strategy: linear
  vars:
    kubectl: /var/lib/rancher/rke2/bin/kubectl
    kubectle_config: /etc/rancher/rke2/rke2.yaml
  tasks:
    - name: Check if uptodated
      ansible.builtin.debug:
        msg: Succeeded   